# Generated by Django 5.2 on 2025-04-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_product_id_product_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='picture_url',
            new_name='picture',
        ),
    ]
