# Generated by Django 5.2 on 2025-11-29 18:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrate_product_dimensions_to_attributes(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    Attribute = apps.get_model('shop', 'Attribute')
    ProductAttribute = apps.get_model('shop', 'ProductAttribute')

    # Create attributes if they don't exist
    weight_attr, _ = Attribute.objects.get_or_create(name='Weight')
    length_attr, _ = Attribute.objects.get_or_create(name='Length')
    width_attr, _ = Attribute.objects.get_or_create(name='Width')
    height_attr, _ = Attribute.objects.get_or_create(name='Height')

    for product in Product.objects.all():
        if product.weight is not None:
            ProductAttribute.objects.create(product=product, attribute=weight_attr, value=str(product.weight))
        if product.length is not None:
            ProductAttribute.objects.create(product=product, attribute=length_attr, value=str(product.length))
        if product.width is not None:
            ProductAttribute.objects.create(product=product, attribute=width_attr, value=str(product.width))
        if product.height is not None:
            ProductAttribute.objects.create(product=product, attribute=height_attr, value=str(product.height))


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_product_height_product_length_product_weight_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.attribute"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "attribute")},
            },
        ),
        migrations.RunPython(migrate_product_dimensions_to_attributes),
        migrations.RemoveField(
            model_name="product",
            name="height",
        ),
        migrations.RemoveField(
            model_name="product",
            name="length",
        ),
        migrations.RemoveField(
            model_name="product",
            name="weight",
        ),
        migrations.RemoveField(
            model_name="product",
            name="width",
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
