# Generated by Django 5.2 on 2025-11-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_attribute_remove_product_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="attributes",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="shop.attribute"
            ),
        ),
    ]
